### ISSUE TITLE
Замечание к первой лабораторной (классификация изображений)

### ISSUE THREAD

**Issue by Cubgl** [CVH4OYC/computervision#1]
К коммиту https://github.com/CVH4OYC/computervision/tree/287c6a25442031f2156eeb1c98eafe6c165b4245

При работе с набором данных CIFAR100 Вы приводите данные в наборе X_train к диапазону  0..1
командой
X_train = X_train / 255.0
Однако, данные в наборе X_test остаются в диапазоне 0..255

Получается, Вы обучаете на данных одной структуры, а проверяете результат обучения на данных другой структуры.

Нужно добавить аналогичное преобразование для X_test. 

Тогда и качество обучения вырастет

**Comment by CVH4OYC** [comment]
Добавил преобразование для X_test (качество выросло) и сравнение метки картинки с предсказанием

**Comment by Cubgl** [comment]
Спасибо за работу! Лабораторная зачтена.
